### PR TITLE
feat: add em an nb-space characters to invisibles

### PR DESCRIPTION
**Pull request by dskamiotis**
## What does this change?

Currently the only nods and characters this library facilitates are hard-break, paragraph and space.

we want to allow Composer to read EM space and NB space aprticualrly when pasting text/articles from other software such as InDesign.
## How to test

We can test locally by running `yarn watch`

To paste the following lines:
em-space: `The quick brown fox jumped over the lazy dog.`
nb-space: `The quick brown fox jumped over the lazy dog.`

The above sentences provide the appropriate spacing.
## How can we measure success?

Images:
Screenshot 2022-09-26 at 13 47 58

### CODE REVIEW

**Comment by jonathonherbert** [comment]
Good to see this. Let's rebase from #52 and remove the em-space.

The position of the nb-space is a bit weird – it's a little too far to the right. Let's aim for something like:

1746636_Screen Shot 2019-05-05 at 8 54 43 5-5-19

Happy to pair to get that right.

**Comment by dskamiotis** [comment]
yes - im a little hesitant to use any CSS padding as that moves the positioning of the text as well

**Comment by dskamiotis** [comment]
Renewed version with CSS:
Screenshot 2022-09-28 at 14 09 19

**Review by jonathonherbert — APPROVED** [review]
👌

**Pull request merged**
